services:
  neo4j:
    image: neo4j:5.24.2
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neotest123"
    volumes:
      - ./neo4j_data:/data